version: '3.8'

services:
  backend:
    build: .
    container_name: affordly-api
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/affordly
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mongodb:
        condition: service_started
    restart: unless-stopped
    networks:
      - proxy-network
      - affordly-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:7
    container_name: affordly-db
    expose:
      - "27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-logs:/var/log/mongodb
    restart: unless-stopped
    networks:
      - affordly-network
    environment:
      - MONGO_INITDB_DATABASE=affordly
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  mongodb-data:
  mongodb-logs:

networks:
  # Internal network for backend <-> mongodb communication
  affordly-network:
    driver: bridge
  
  # External network shared with Nginx
  proxy-network:
    external: true